main-class=com.ebstrada.formreturn.server.ServerGUI
main-jar=formreturn.jar
icon=icons/formreturn_server.icns
java-options=--add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.desktop/com.apple.laf=ALL-UNNAMED -Dapple.laf.useScreenMenuBar=true -Dcom.apple.macos.use-file-dialog-packages=true -Dcom.apple.macos.useScreenMenuBar=true -Dcom.apple.smallTabs=true -Dfile.encoding=UTF-8 -Xmx512M
